### ISSUE TITLE
Drop Analytics

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-analytics-go#1]
# Goal

Users have access to varies drops analytics.

# Service Requirements

- Setup influx DB
- go service that subscribes to redpanda
- Define and create influx DB buckets

# Drop Analytics Requirements

- Number of NFTs minted for a collection over time range

![Image](https://user-images.githubusercontent.com/2388118/219106441-a591b8fb-bc20-45e5-b7d4-8809c5c3c7de.png)

- Percent change of number of nfts minted

![Image](https://user-images.githubusercontent.com/2388118/219106366-c91198c8-b21e-4775-aa9e-eb4d97e19f67.png)

- Avg minted per time frame hour, day, week, month

![Image](https://user-images.githubusercontent.com/2388118/219106663-3ffe730d-2f7f-4a18-97bb-30d3ccb23be7.png)

- Unique minters over time frame

![Image](https://user-images.githubusercontent.com/2388118/219106904-0aedcb37-d371-4808-9f2c-2468629e3717.png)

**Comment by kespinola** [comment]
```graphql

query {
  project(id: {project}) {
    drop(id: {drop}) {
      stats(startDate: "", dateDate: "") {
          mints {
             current
             previous
          }
      }
      collection {
         timeseries {
           mints(starteDate: "", endDate: "", batchSize: "HOURLY| DAILY|MONTHLY") {
             timestamp
             amount
          }
        }
      }
    }
  }
}
```

**Comment by kespinola** [comment]
I've reached out to different agencies mentioned on the influxdb site for quotes on finishing analytics.

**Comment by kespinola** [comment]
Research cubes a quicker and more aligned means of adding analytics to HUB.

**Comment by mpwsh** [comment]
hub-analytics moved to use cubejs
